/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pwolfgang_numjava_DotProduct */

#ifndef _Included_com_pwolfgang_numjava_DotProduct
#define _Included_com_pwolfgang_numjava_DotProduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pwolfgang_numjava_DotProduct
 * Method:    intXintInnerProduct
 * Signature: (IIIII[I[I)I
 */
JNIEXPORT jint JNICALL Java_com_pwolfgang_numjava_DotProduct_intXintInnerProduct
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray, jintArray);

/*
 * Class:     com_pwolfgang_numjava_DotProduct
 * Method:    intXfloatInnerProduct
 * Signature: (IIIII[I[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_pwolfgang_numjava_DotProduct_intXfloatInnerProduct
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jintArray, jfloatArray);

/*
 * Class:     com_pwolfgang_numjava_DotProduct
 * Method:    floatXfloatInnerProduct
 * Signature: (IIIII[F[F)F
 */
JNIEXPORT jfloat JNICALL Java_com_pwolfgang_numjava_DotProduct_floatXfloatInnerProduct
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jfloatArray, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
